
import { VideoInsight } from "../types";

// Note: jsPDF is loaded via script tag in index.html to avoid complex bundling issues
declare const jspdf: any;

export const downloadHowToPdf = (insight: VideoInsight) => {
  if (!insight.howToSteps || insight.howToSteps.length === 0) return;

  const doc = new jspdf.jsPDF();
  const margin = 20;
  let cursorY = 20;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("How-To Guide", margin, cursorY);
  cursorY += 12;

  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text(insight.title, margin, cursorY);
  cursorY += 20;

  // Summary Header
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Video Summary", margin, cursorY);
  cursorY += 10;

  // Summary Content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const summaryLines = doc.splitTextToSize(insight.summary, 170);
  doc.text(summaryLines, margin, cursorY);
  cursorY += (summaryLines.length * 6) + 15;

  // Steps Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Step-by-Step Instructions", margin, cursorY);
  cursorY += 12;

  // Steps Content
  insight.howToSteps.forEach((item, index) => {
    if (cursorY > 260) {
      doc.addPage();
      cursorY = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`${index + 1}. ${item.step}`, margin, cursorY);
    cursorY += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const descLines = doc.splitTextToSize(item.description, 170);
    doc.text(descLines, margin, cursorY);
    cursorY += (descLines.length * 5) + 8;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by TubeSummarist Pro - ${new Date().toLocaleDateString()}`, margin, 285);

  doc.save(`${insight.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_guide.pdf`);
};
